<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_goto_mygits</name>
   <tag></tag>
   <elementGuidId>e6ef0211-6f93-4b5b-8784-6f81ee8d1d44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;gist-pjax-container&quot;]/div/div/div[2]/div[2]/div[1]/div/div[2]/span[1]/a[2]/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
