<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_komen_gits</name>
   <tag></tag>
   <elementGuidId>8f710078-31f1-4d8c-b5b1-376438761865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;gists&quot;]/div[2]/div/div[2]/div/div[5]/div[1]/div/div/div/div[5]/div/pre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
